name: OnyxAdmin
main: me.maveronyx.onyxadmin.OnyxAdmin
version: 0.1
commands:
   warn:
      description: Warn a player. If a player is warned 3 times, he/she will be kicked.
      usage:
           /<command> [Player]
   kick:
      description: Kick a player.
      usage:
           /<command> [Player]
   ban:
      description: Ban a player.
      usage:
           /<command> [Player]
   freeze:
      description: Freeze a player.
      usage:
           /<command> [Player]
permissions:
    onyxadmin.*:
        description: Gives access to all OnyxAdmin commands
        children:
            onyxadmin.warn.*: true
            onyxadmin.kick.*: true
            onyxadmin.ban.*: true
            onyxadmin.freeze.*: true